services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abogada-rebeca-app
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
